# Generated by Django 4.1.5 on 2023-02-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='image',
            field=models.ImageField(default='', upload_to='users/'),
        ),
    ]
